// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMYqDiSimK4yyKx6mCXeYptTiuDwSGsRA',
    appId: '1:521403190755:web:2926bc085033e48b6da4d6',
    messagingSenderId: '521403190755',
    projectId: 'discuss-hub-project',
    authDomain: 'discuss-hub-project.firebaseapp.com',
    storageBucket: 'discuss-hub-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzaqPLrCTDFl37ye63-x6q7PpxH2fmbgk',
    appId: '1:521403190755:android:6a39f82afc89a43b6da4d6',
    messagingSenderId: '521403190755',
    projectId: 'discuss-hub-project',
    storageBucket: 'discuss-hub-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4x3QR_xq5VuMxDtAqPufQvziHPLHvLw',
    appId: '1:521403190755:ios:99064e96c2c988ac6da4d6',
    messagingSenderId: '521403190755',
    projectId: 'discuss-hub-project',
    storageBucket: 'discuss-hub-project.firebasestorage.app',
    iosBundleId: 'com.example.discussHubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4x3QR_xq5VuMxDtAqPufQvziHPLHvLw',
    appId: '1:521403190755:ios:99064e96c2c988ac6da4d6',
    messagingSenderId: '521403190755',
    projectId: 'discuss-hub-project',
    storageBucket: 'discuss-hub-project.firebasestorage.app',
    iosBundleId: 'com.example.discussHubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMYqDiSimK4yyKx6mCXeYptTiuDwSGsRA',
    appId: '1:521403190755:web:f4760b001c04c3716da4d6',
    messagingSenderId: '521403190755',
    projectId: 'discuss-hub-project',
    authDomain: 'discuss-hub-project.firebaseapp.com',
    storageBucket: 'discuss-hub-project.firebasestorage.app',
  );
}
